Donatello/Models/Board.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Donatello.Models
{
   public class Board
   {
      public int Id { get; set; }
      public string Title { get; set; }
      public List<Column> Columns { get; set; } = new List<Column>();
   }
}

Donatello/ViewModels/BoardView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Donatello.ViewModels
{
    public class BoardView
    {
        public int Id { get; set; }
        public string BoardTitle { get; set; }
        public List<Column> Columns { get; set; } = new List<Column>();
        public class Column
        {
            public string Title { get; set; }

            public List<Card> Cards { get; set; } = new List<Card>();
        }

        public class Card
        {
            public int Id { get; set; }
            public string Content { get; set; }
        }
    }
}

Donatello/Controllers/BoardController.cs
using Donatello.Services;
using Donatello.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Donatello.Controllers
{
    public class BoardController : Controller
    {
        private readonly BoardService boardService;

        public BoardController(BoardService boardService)
        {
            this.boardService = boardService;
        }

        public IActionResult Index(int id)
        {
            BoardView model = boardService.GetBoard(id);

            return View(model);
        }

        public IActionResult AddCard(int id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCard(NewCard vm)
        {
            if (ModelState.IsValid)
            {
                boardService.AddCard(vm);
                return RedirectToAction(nameof(Index), new { id = vm.Id });
            }
            return View(vm);
        }
    }
}

Donatello/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Donatello.Services;
using Donatello.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Donatello.Controllers
{
    public class CardController : Controller
    {
        private readonly CardService _cardService;

        public CardController(CardService cardService)
        {
            _cardService = cardService;
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            CardDetails vm = _cardService.GetCardDetails(id);
            return View(vm);
        }

        [HttpPost]
        public IActionResult Update(CardDetails details)
        {
            if (ModelState.IsValid)
            {
                _cardService.Update(details);
                TempData["Message"] = "Card saved";
                return RedirectToAction(nameof(Details), new { id = details.Id });
            }
            return View();
        }
    }
}

Donatello/Views/Board/AddCard.cshtml
@model Donatello.ViewModels.NewCard
@{
    ViewData["Title"] = "AddCard";
}

<div class="container">
    <div class="row">
        <h2>Add Card</h2>
        <form method="post" asp-action="AddCard" asp-controller="Board">
            <div asp-validation-summary="All" class="text-danger"></div>
            <label asp-for="Contents"></label>
            <input type="text" asp-for="Contents" />
            <button type="submit" class="btn">Add</button>
        </form>
    </div>

</div>

Donatello/Views/Board/Index.cshtml
@model Donatello.ViewModels.BoardView
@{
    ViewData["Title"] = "Board View";
}

<div class="container">

    @if (Model.Columns.Count > 0)
    {
        <a asp-controller="Board"
           asp-action="AddCard"
           asp-route-id="@Model.Id"
           class="waves-effect waves-light btn">
            Add Card
        </a>
    }
    <div class="row">
        <h2>@Model.BoardTitle</h2>
    </div>
    <div class="row">
        @foreach (var column in Model.Columns)
        {
            <div id="target" ondrop="drop_handler(event);" ondragover="dragover_handler(event);" class="col m2">
                <h3>@column.Title</h3>
                @foreach (var card in column.Cards)
                {<a asp-controller="Card" asp-action="Details"
                    asp-route-id="@card.Id" class="white-text">
                    <div id="p1" draggable="true" ondragstart="dragstart_handler(event);" class="card blue-grey darken-1">
                        <div class="card-content white-text">
                            <p>@card.Content</p>
                        </div>
                    </div>
                </a>
                }
            </div>
        }
    </div>
</div>